version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:${MONGO_PORT}
  app:
    container_name: app
    restart: always
    build:
      context: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - 4005:4005
    external_links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local
